config/routes.rb
OneteamApp::Application.routes.draw do

  resources :requests do
    get :cancel_request
  end

  get "cancel_request" => "requests#cancel_request", :as => "cancel_request"
 
  resources :skills

  get "calendars/index"

  get "password_resets/new"

  resources :feedbacks
  resources :commissions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "employees#new", :as => "sign_up"
  get "my_requests" => "requests#my_requests", :as => "_my_requests"
  get "requests_calendar" => "requests#requests_calendar", :as => "_requests_calendar"
  get "my_requests_calendar" => "requests#my_requests_calendar", :as => "_my_requests_calendar"
  root :to => "sessions#new" 
  
  resources :requests do 
    resources :responses 
  end

  resources :responses do
      resources :commissions
  end 

  resources :employees
  resources :sessions
  resources :requests
  resources :responses
  resources :password_resets

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_secure_password

  attr_protected :password_salt, :password_hash 
  attr_accessible :employee_id, :password, :password_confirmation, :department, :email, :group, :location, :manager, :first_name, :last_name, :description, :position, :current_skills, :skills_interested_in, :years_with_company, :image

  before_save :encrypt_password

  has_many :requests, dependent: :destroy
  belongs_to :request

  has_many :responses, :through => :requests
  has_many :commissions, :through => :responses
  
  accepts_nested_attributes_for :requests
  accepts_nested_attributes_for :responses

  has_and_belongs_to_many :skills
  belongs_to :skills   

  mount_uploader :image, ImageUploader
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates :password, :length => { :in => 5..20 }, :on => :create
  validates_presence_of :email, :first_name, :last_name  
  validates_uniqueness_of :email, :first_name and :last_name

  before_create { generate_token(:auth_token) }

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    EmployeeMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Employee.exists?(column => self[column])
  end

  def self.authenticate(email, password)
    employee = find_by_email(email)
    if employee && employee.password_hash == BCrypt::Engine.hash_secret(password, employee.password_salt)
      employee
    else
      nil
    end
  end      

  def encrypt_password
  	if password.present?
  		self.password_salt = BCrypt::Engine.generate_salt
  		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  	end	
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
respond_to :html, :json
before_filter :signed_in_employee, only: [:edit, :update, :index]
before_filter :current_employee
before_filter :check_for_cancel, :only => [:create, :update]

  def index
    @employees = Employee.order(:id).page(params[:page]).per(10)

    respond_with(@employees)
  end

  def show
    @employee = Employee.find(params[:id])
    @requests = Request.all
    @commissions = Commission.all
    @my_commissions = Commission.order(:id).page(params[:page]).per(5)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  def new
    @employee = Employee.new
    @skills = Skill.all

    respond_with(@employee)
  end

  def edit
    @employee = Employee.find(params[:id])
    @skills = Skill.all
    
    current_skills = params[:current_skills]

    if !params[:current_skills].nil?
      current_skills = @employee.current_skills.split(", ")
    end

    skills_interested_in = params[:skills_interested_in]

    if !params[:skills_interested_in].nil?
      skills_interested_in = @employee.skills_interested_in.split(", ")
    end

  end

  def create
    @employee = Employee.new(params[:employee])
    @skills = Skill.all
     
    if params[:cancel_button]
      redirect_to root_url
    elsif @employee.save
      flash[:notice] = "Successfully created account profile."
      redirect_to root_url, :notice => "Your account was created. Sign in!"
    elsif !@employee.save
      render "new"
    end
  end

  def update
    @employee = Employee.find(params[:id])
    @skills = Skill.all

    @employee.current_skills = params[:current_skills].to_a
    @employee.current_skills = @employee.current_skills.join(", ")

    @employee.skills_interested_in = params[:skills_interested_in].to_a
    @employee.skills_interested_in = @employee.skills_interested_in.join(", ")

    if params[:cancel_button]
      redirect_to @employee
    elsif @employee.update_attributes(params[:employee])
      respond_to do |format|
        format.html { redirect_to @employee, notice: 'Employee profile was successfully updated.' }
        format.json { head :no_content }
      end  
    elsif !@employee.update_attributes(params[:employee])
      respond_to do |format|
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    
    respond_with(@employee)
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper

def gravatar_for(employee)
    gravatar_id = Digest::MD5::hexdigest(employee.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: employee.first_name, class: "gravatar")
end

end

app/views/employees/_form.html.erb
<div id="emp-form">

<%= hidden_field_tag "employee[current_skills][]", "" %>
<%= hidden_field_tag "employee[skills_interested_in][]", "" %>

<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="emp-first">
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
</div>
<div id="emp-second">  
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
</div>

<div id="emp-third">
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
</div>
<div id="emp-fourth">  
  <div class="field">
    <%= f.label :office %>
    <%= f.select :location, ['New York', 'Chicago', 'Los Angeles', 'Atlanta', 'Detroit', 'Boston', 'Mumbai', 'Houston'] %>
  </div>
</div>

<div id="emp-fifth">  
  <div class="field">
    <%= f.label :department %>
    <%= f.select :department, ['IT', 'HR', 'R&D'] %>
  </div>
</div>

<div id="emp-sixth">
  <div class="field">
    <%= f.label :group %>
    <%= f.select :group, ['Development', 'Design', 'QA'] %>
  </div>
</div>

<div id="emp-seventh">
 <div class="field">
    <%= f.label :job_title %>
    <%= f.select :position, ['Engineer', 'Analyst', 'Supervisor'] %>
  </div>
</div>
<div id="emp-eighth">  
  <div class="field">
    <%= f.label :immediate_supervisor %>
    <%= f.text_field :manager %>
  </div>
</div>
<div id="emp-ninth">  
  <div class="field">
    <%= f.label :years_with_company %>
    <%= f.select :years_with_company, ['1','2','3','4','5','6','7','8','9','10-15','16-20', '21-25', '25-30'] %>
  </div>
</div>
<div id="emp-tenth">     
  <div id="emp-description">
    <div class="field">
      <%= f.label :description %><br/>
      <%= f.text_area :description, :size => "55x6" %>
    </div>
  </div>
</div>
<div id="emp-eleventh">
  <%= image_tag @employee.image_url, :height => 80 %></br>
  <%= "Upload Your Photo" %>
   <%= f.file_field :image %></br>
</div>

<div id="emp-twelfth">
  <div class="field">
    <%= f.label :current_skills %>
    <% @skills.each do |skill| %>
      <div class="inbox">       
       <%= check_box_tag "current_skills[]", skill.language, @employee.current_skills.include?(skill.language) %>
        <div class = "language">
         <%= skill.language %>
        </div>
     </div>
    <% end %>
  </div>
</div>

<div id="emp-thirteenth">
   <div class="field">
     <%= f.label :skills_interested_in, "Desired skills" %>
      <% @skills.each do |skill| %>
      <div class="inbox">
         <%= check_box_tag "skills_interested_in[]", skill.language, @employee.skills_interested_in.include?(skill.language) %>
       <div class = "language">
         <%= skill.language %>
        </div>
     </div>
    <% end %>
  </div>
</div>    
   
<div id="emp-fourteenth">
  <div class="actions">
    <%= f.submit "Update Profile", class: "btn btn-large btn-primary" %>
  </div>
  <div class="emp-cancel-update">
    <%= f.submit 'Cancel', :action => 'update', :name => 'cancel_button' %>
  </div>
    <% end %>
</div>
</div>

</div> 

app/views/employees/edit.html.erb
<div id="tabs"> 
  <ul>
    <li><%= link_to 'All Requests', requests_path%></li>
    <li><%= link_to "Requests I've Posted",  _my_requests_path %></li>
    <li id="selected"><%= link_to 'Update My Profile', edit_employee_path(current_employee) %></li>
  </ul>
</div>

<div id="innercontainer">
</br>

  <h1>Update Profile</h1>

  <%= render 'form' %>

</div>
 

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
    <li><%= link_to 'All Requests', requests_path%></li>
    <li><%= link_to "Requests I've Posted",  _my_requests_path %></li>
    <li id="selected"><%= link_to 'Employees List', edit_employee_path(current_employee) %></li>
  </ul>
</div>

<div id="innercontainer">
<h1>Employees List</h1>

<%= paginate @employees %>
<table>
  <tr>
    <th>Avatar</th>
    <th>Employee ID</th>
    <th>Employee Name</th>
    <th>Email</th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= image_tag employee.image_url, :height => 25 %></td>
    <td><%= employee.id %></td>
    <td><%= employee.first_name %> <%= employee.last_name %></td>
    <td><%= employee.email %></td>
    <td><%= link_to 'Show', employee %></td>
    <% if owner? (employee) %>
      <td><%= link_to 'Update Profile', edit_employee_path(employee) %></td>
      <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>
<p></p>
</div>

app/views/employees/new.html.erb
<p></p>
<div id="innercontainer">

<h2>Sign up for your OneTeam Account</h2>

<%= hidden_field_tag "employee[current_skills][]", "" %>
<%= hidden_field_tag "employee[skills_interested_in][]", "" %>

<%= form_for(@employee) do |f| %>
  <div class="frstnm">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="lnfield">
    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
  </div>
  <div class="newfirst">
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="passfld">
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
  </div>
 <div class="newsecond">
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>      
      <%= f.hidden_field :current_skills, :value => "" %>
      <%= f.hidden_field :skills_interested_in, :value => "" %>
</div>
 
<div id="new-emp">
 <div class="actions">
    <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
  </div>  
  <div class="emp-cancel-new">
    <%= f.submit 'Cancel', :action => 'create', :name => 'cancel_button' %>
  </div>
  <% end %>
</div>

</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
    <li><%= link_to 'All Requests', requests_path%></li>
    <li><%= link_to "Requests I've Posted",  _my_requests_path %></li>
    <li id="selected"><%= link_to 'Profile', employee_path(current_employee) %></li>
  </ul>
</div>

<div id="innercontainer">
  <div id="emp-left-column">
    <div id="profile_pic">
      <%= link_to 'Update Profile', edit_employee_path(current_employee) %> </br>
      <%= image_tag @employee.image_url, :height => 100 %>
    </div>
  </div>
  <div id = "emp-right-column">
    <div id = "profile">
      <ul>
        <li>First Name: <%= @employee.first_name %></li>
        <li>Last Name: <%= @employee.last_name %></li>
        <li>Email: <%= @employee.email %></li>
        <li>Office: <%= @employee.location %></li>
        <li>Department: <%= @employee.department %></li>
        <li>Group: <%= @employee.group %></li>
        <li>Job Title: <%= @employee.position %></li>
        <li>Immediate Supervisor: <%= @employee.manager %></li>
        <li>Years with Company: <%= @employee.years_with_company %></li>
      </ul>
      <ul>
        <li>Current Skills: <%= @employee.current_skills %></li>
        <li>Desired Skills: <%= @employee.skills_interested_in %></li>
      </ul>
      <ul>
        <li>Short Description about <%= @employee.first_name %>: <%= @employee.description %></li>
      </ul> 
      <ul>
        <li>Projects I've Worked on:</li>  
      </ul>
      <ul>
        <%= paginate @my_commissions %>
        <% @commissions.each do |commission| %>
          <% if commission.employee_id == current_employee.id %>
            <li><b><%= Request.find(commission.request_id).title %></b>: <%= Request.find(commission.request_id).start_date %> to <%= Request.find(commission.request_id).end_date %> (<%= Request.find(commission.request_id).project_status %>)</br></li>
            <li><%= Request.find(commission.request_id).description %></li>
            <%= image_tag "divider-line-2.jpg" %>            
          <% end %>
        <% end %>
      </ul>
    </div>  
  </div>
</div>