config/routes.rb
OneteamApp::Application.routes.draw do

  resources :requests do
    get :cancel_request
  end

  get "cancel_request" => "requests#cancel_request", :as => "cancel_request"
 
  resources :skills

  get "calendars/index"

  get "password_resets/new"

  resources :feedbacks
  resources :commissions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "employees#new", :as => "sign_up"
  get "my_requests" => "requests#my_requests", :as => "_my_requests"
  get "requests_calendar" => "requests#requests_calendar", :as => "_requests_calendar"
  get "my_requests_calendar" => "requests#my_requests_calendar", :as => "_my_requests_calendar"
  root :to => "sessions#new" 
  
  resources :requests do 
    resources :responses 
  end

  resources :responses do
      resources :commissions
  end 

  resources :employees
  resources :sessions
  resources :requests
  resources :responses
  resources :password_resets

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :language
  has_and_belongs_to_many :employees
  belongs_to :employees
  belongs_to :requests
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skills }
    end
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    @skill = Skill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/new
  # GET /skills/new.json
  def new
    @skill = Skill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/1/edit
  def edit
    @skill = Skill.find(params[:id])
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(params[:skill])

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render json: @skill, status: :created, location: @skill }
      else
        format.html { render action: "new" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /skills/1
  # PUT /skills/1.json
  def update
    @skill = Skill.find(params[:id])

    respond_to do |format|
      if @skill.update_attributes(params[:skill])
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy

    respond_to do |format|
      format.html { redirect_to skills_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= simple_form_for(@skill) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :language %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
    <li id="selected"><%= link_to 'Edit Skill', skills_path %></li>
    <li><%= link_to 'Requests', requests_path %></li>
    <li><%= link_to "Requests I've Posted", requests_path%></li>   
    <li><%= link_to 'My Profile', employee_path(current_employee) %></li> 
  </ul>
</div>

<div id="innercontainer">

<h1>Editing skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

</div>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
    <li id="selected"><%= link_to 'Skills', skills_path %></li>
    <li><%= link_to 'Requests', requests_path %></li>
    <li><%= link_to "Requests I've Posted", requests_path%></li>   
    <li><%= link_to 'My Profile', employee_path(current_employee) %></li> 
  </ul>
</div>

<div id="innercontainer">

<h1>Programming Languages</h1>

<p>
<%= link_to 'Add A Language', new_skill_path %>
</p>
<table>
  <tr>
    <th>Language</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @skills.each do |skill| %>
  <tr>
    <td><%= skill.language %></td>
    <td><%= link_to 'Show', skill %></td>
    <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
    <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

</div> 

app/views/skills/new.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
    <li id="selected"><%= link_to 'New Skill', new_skill_path %></li>
    <li><%= link_to 'Requests', requests_path %></li>
    <li><%= link_to "Requests I've Posted", requests_path%></li>   
    <li><%= link_to 'My Profile', employee_path(current_employee) %></li> 
  </ul>
</div>

<div id="innercontainer">

<h1>New Language</h1>

<%= render 'form' %>

<%= link_to 'Back to Skills', skills_path %>

</div>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
    <li id="selected"><%= link_to 'Skill', skill_path %></li>
    <li><%= link_to 'Requests', requests_path %></li>
    <li><%= link_to "Requests I've Posted", requests_path%></li>   
    <li><%= link_to 'My Profile', employee_path(current_employee) %></li> 
  </ul>
</div>

<div id="innercontainer">
	
<p>
  <b>Language:</b>
  <%= @skill.language %>
</p>


<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>

</div>