config/routes.rb
OneteamApp::Application.routes.draw do

  resources :requests do
    get :cancel_request
  end

  get "cancel_request" => "requests#cancel_request", :as => "cancel_request"
 
  resources :skills

  get "calendars/index"

  get "password_resets/new"

  resources :feedbacks
  resources :commissions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "employees#new", :as => "sign_up"
  get "my_requests" => "requests#my_requests", :as => "_my_requests"
  get "requests_calendar" => "requests#requests_calendar", :as => "_requests_calendar"
  get "my_requests_calendar" => "requests#my_requests_calendar", :as => "_my_requests_calendar"
  root :to => "sessions#new" 
  
  resources :requests do 
    resources :responses 
  end

  resources :responses do
      resources :commissions
  end 

  resources :employees
  resources :sessions
  resources :requests
  resources :responses
  resources :password_resets

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :description, :status, :start_date, :end_date, :employee_id, :title, :relevant_skills, :location, :group
  belongs_to :employee
  default_scope order("created_at DESC")  

  has_many :responses, :dependent => :destroy
  accepts_nested_attributes_for :responses, :allow_destroy => true

  has_many :commissions, :through => :responses
  belongs_to :commission

  has_and_belongs_to_many :skills
  belongs_to :skills

  validates_presence_of :title
  validates :description, :length => { :in => 5..200 }

  def get_responses
    Response.where(:request_id => id)
  end

  def get_commissions
    Commission.where(:request_id => id)
  end

  def project_status 
    if status == 'Cancelled'
       "Cancelled"
    elsif end_date <= Date.today 
      "Closed, Completed"
    elsif end_date <= Date.today 
      "Expired"   
    elsif start_date <= Date.today 
      "Open, In progress"
    elsif start_date >= Date.today 
      "Open, Not Started"  
    elsif start_date >= Date.today   
      "Assigned"
    end
  end 

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
 respond_to :html, :json
 before_filter :signed_in_employee
 before_filter :check_for_cancel, :only => [:create, :update]

  def cancel_request
    @request = Request.find_by_employee_id(current_employee)
   
    project_status = "CANCELLED"
    @request.save

    respond_with(@my_requests)
  end

  def my_requests
    @requests = Request.find_all_by_employee_id(current_employee)
    @my_requests = Request.order(:id).page(params[:page]).per(5) 
  end

  def requests_calendar
    @requests = Request.order(:id).page(params[:page]).per(5)
    @requests_by_date = @requests.group_by(&:start_date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def my_requests_calendar
    @requests = Request.order(:id).page(params[:page]).per(5)
    @requests_by_date = @requests.group_by(&:start_date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def index
    @requests = Request.order(:id).page(params[:page]).per(5)
    @commissions = Commission.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  def show
    @request = Request.find_by_employee_id(current_employee)
    @skills = Skill.all
    relevant_skills = params[:relevant_skills]

    if !params[:relevant_skills].nil?
      relevant_skills = @request.relevant_skills.split(", ")
    end
    
  end

  def new
    @request = Request.new
    @skills = Skill.all  

    respond_with(@request)
  end

  def edit 
    @request = Request.find(params[:id])
    @skills = Skill.all

    relevant_skills = params[:relevant_skills]

    if !params[:relevant_skills].nil?
      relevant_skills = @request.relevant_skills.split(", ")
    end

  end

  def create
    @request = current_employee.requests.build(params[:request])
    @skills = Skill.all 

     @request.relevant_skills = params[:relevant_skills].to_a
     @request.relevant_skills = @request.relevant_skills.join(", ")


    if params[:cancel_button]
      redirect_to _my_requests_path
    elsif @request.save     
      respond_to do |format|
          format.html { redirect_to requests_path, notice: 'Request was successfully created.' }
          format.json { render json: @request, status: :created, location: @request }
      end
    elsif !@request.save
      respond_to do |format|
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @request = Request.find(params[:id])
    @skills = Skill.all

    @request.relevant_skills = params[:relevant_skills].to_a
    @request.relevant_skills = @request.relevant_skills.join(", ")

    if params[:cancel_button]
      redirect_to _my_requests_path
    elsif @request.update_attributes(params[:request])
      flash[:success] = "Request cancelled."
      redirect_to _my_requests_path
    elsif @request.update_attributes(params[:request])
      flash[:success] = "Request updated"
      redirect_to _my_requests_path
    else
      render 'edit'
    end

  end 

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    respond_with(@request)
  end

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= hidden_field_tag "request[relevant_skills][]", "" %>

<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <div class = "req-description">
      <%= f.label :description %>
      <%= f.text_area :description, :size => "40x6" %>
    </div>
  <div>

  <div class="field">
    <%= f.hidden_field :employee_id, :value => current_employee.id %>
  </div>
   
  <div class="req-dates">
    <div id="field">
      <%= f.label :start_date %>
      <%= f.text_field :start_date %>
    </div>
  </div>
  <div class="req-dates">
    <div id="field">
      <%= f.label :end_date %>
      <%= f.text_field :end_date %>
    </div>
  </div>

 <div class = "req-select-checkboxes"> 
 <div class="field" id="left-column">
    <ul>
      <li><%= f.label :group %></li>
      <li><%= f.select :group, ['Development', 'Strategy'] %></li>
    </ul>
  </div>
  <div class="field" id="right-column" >
    <ul> 
      <li><%= f.label :location, "Office" %></li>
      <li><%= f.select :location, ['NY', 'AR', 'IL', 'UK', 'CA'] %></li>
    </ul>
  </div>
  
 <%= f.label :relevant_skills  %>
     <% @skills.each do |skill| %>
    <div class = "inbox">
       <%= check_box_tag "relevant_skills[]", skill.language, @request.relevant_skills.include?(skill.language) %>
       <div class = "language">
         <%= skill.language %>
        </div>
    </div> 
     <% end %>
  </div>

  <div id="req-edit">
    <div class="actions">
      <%= f.submit %>
    </div>
    <% end %>
  </div>

</div>

app/views/requests/cancel_request.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
    <li><%= link_to 'All Requests', requests_path%></li>
    <li id="selected"><%= link_to "Cancel My Request" %></li>
    <li><%= link_to "Requests I've Posted", _my_requests_path %></li>
    <li><%= link_to 'My Profile', employee_path(current_employee) %></li>     
  </ul>
</div>

<div id="innercontainer">

<div id="question">
	<p>Are you sure you want to cancel this request?</p>
</div>

<p>
  <b>Request:</b> <%= @request.title %> (<%= @request.start_date %> to <%= @request.end_date %>)
</p>
<p>
  <%= @request.description %>
</p>
<p>
  <b>Relevant Skills:</b> <%= @request.relevant_skills %>
</p>

<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibitied this request from being saved:</h2>
      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  

  <%= f.hidden_field :status, :value => 'cancelled' %>

  <div class="actions">
    <div id="cancel-req">
      <%= f.submit 'Cancel Request' %>
    </div>
    <div class="req-cancel-new">
      <%= f.submit "Don't Cancel Request", :action => 'update', :name => 'cancel_button' %>
    </div>
<% end %>
  </div>

</div>

app/views/requests/edit.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
    <li id="selected"><%= link_to 'Update Request', edit_request_path(@request) %></li>
    <li><%= link_to 'All Requests', requests_path%></li>  
    <li><%= link_to "Requests I've Posted", _my_requests_path %></li>  
    <li><%= link_to 'My Profile', employee_path(current_employee) %></li> 
  </ul>
</div>

<div id="innercontainer">

<h1>Update request</h1>

<%= render 'form' %>
<p></p>

</div>
</div>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs">
  <ul>
    <li id="selected"><%= link_to 'All Requests', requests_path%></li>
    <li><%= link_to "Requests I've Posted", 'my_requests' %></li>
    <li><%= link_to 'My Profile', employee_path(current_employee) %></li>
  </ul>
</div>

<div id="innercontainer">
<p><%= link_to 'Create New Request', new_request_path %></p>

<h1>All Requests</h1><%= link_to "View Calendar", 'requests_calendar' %>

<div id="requests">
  <%= paginate @requests %>
  <% @requests.each do |request| %>
    <% if request.status == 'cancelled' %>
      <% nil %>
    <% elsif request.status != 'cancelled' %>
      <%= image_tag "divider-line.jpg" %>

      <p><b><%= request.title %>:</b> <%= request.start_date %> to <%= request.end_date %> (Status: <%= request.project_status %>)
      </p>
      <p>Posted by: <%= request.employee.first_name %> <%= request.employee.last_name %> in <%= request.employee.location %> Office (Group: <%= request.employee.group %>) </br>
        Description: <%= request.description %></br>
        Required Skills: <%= request.relevant_skills %>
      </p> 
      <% applied = 0 %>

        <% commissions = request.get_commissions %>
        <% if !commissions.blank? %>
          <div id = "note">
            <%= "Developer already selected" %>
          </div> 
        <% else %>
          <% if author? (request) %>
            <div id = "note">
              <%= "You posted this request." %>
            </div>
          <% else %>
            <% responses = request.get_responses %>
            <% responses.each do |response| %>     
            <% if response.employee_id == current_employee.id %>
              <div  >
                <%= image_tag "applied_button.jpg" %>
              </div>
              <% applied = 1 %>
            <% end %>
          <% end %>
          <% if applied == 0 %>
            <div id="apply-button">
              <%= link_to image_tag("apply_button.jpg"), new_request_response_path(request) %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</br>
</br>
</div>

app/views/requests/my_requests.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
    <li><%= link_to 'All Requests', requests_path%></li>
    <li id="selected"><%= link_to "Requests I've Posted" %></li>
    <li><%= link_to 'My Profile', employee_path(current_employee) %></li>     
  </ul>
</div>

<div id="innercontainer">

<p><%= link_to 'Create New Request', new_request_path %></p>

<h1>Requests I've Posted:</h1><%= link_to "View Calendar", 'my_requests_calendar' %>

<div id="requests">
  <%= paginate @my_requests %>

<% @requests.each do |request| %>

  <%= image_tag "divider-line.jpg" %>
  <p><h3><%= request.title %></h3> <%= request.start_date %> to <%= request.end_date %> 
    (Status: <% if request.status.nil? %>
               <%= request.project_status%>)</br>
             <% else %>
               <%= request.status %>)</p>
             <% end %>
   Posted by: <%= Employee.find(request[:employee_id]).first_name %> <%= Employee.find(request[:employee_id]).last_name %> in <%= Employee.find(request[:employee_id]).location %> Office (Group: <%= Employee.find(request[:employee_id]).group %>)</br>
    Description: <%= request.description %></br>
    Required Skills: <%= request.relevant_skills %></br>

  <% if request.status == 'cancelled' %>
    <div id = "note"><%= "Cancelled" %></div></br>
  <% else %>
    <% commissions = request.get_commissions %>
    <% if commissions.blank? %>
      <%= link_to 'Edit', edit_request_path(request, @response) %>  |
      <%= "Active" %>  |      
      <%= link_to 'Cancel', :action => :cancel_request  %>
    <% end %>
  <% end %>
          
</p>
    <b>Applicants:</b></br>
    <% responses = request.get_responses %>
    <% responses.each do |response| %>
    <%= response.employee_name %>   |  
    <%= link_to 'View Profile', employee_path(response.employee_id) %>  |    
      <% commissions = request.get_commissions %>
      <% if commissions.blank? == false %>
        <% commissions.each do |commission| %>  
          <% if response.employee_id == commission.employee_id %>
            <%= "Selected" %> 
          <% end %>
        <% end %>  
      <% elsif response.blank? == false  %>
        <%= link_to "Select Developer", new_response_commission_path(response) %>
      <% end %>    
</p>
    <% end %>
  <% end %>
</div>

</div>

app/views/requests/my_requests_calendar.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
    <li><%= link_to 'All Requests', requests_path%></li>
    <li id="selected"><%= link_to "Requests I've Posted",  'my_requests_calendar' %></li>
    <li><%= link_to 'My Profile', employee_path(current_employee) %></li> 
  </ul>
</div>

<div id="innercontainer">

<h1>My Requests Calendar</h1><%= link_to "View List", requests_path %>
<div id="requests">


  <h2 id="month">
    <%= link_to "<", date: @date.prev_month %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", date: @date.next_month %>
  </h2>

  <%= calendar @date do |date| %>
    <%= date.day %>
    
      <% if @requests_by_date[date] %>
        <ul>
          <% @requests_by_date[date].each do |request| %>
            <% if author? (request) %>
              <li><%= link_to request.title, request %></li>
            <% end %>  
          <% end %>
        </ul>
      <% end %> 
  <% end %>

</br>
</div>

app/views/requests/new.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
  	<li id="selected"><%= link_to 'New Request' %></li>
    <li><%= link_to 'All Requests', requests_path%></li>
    <li><%= link_to "Requests I've Posted", _my_requests_path %></li>
    <li><%= link_to 'My Profile', employee_path(current_employee) %></li> 
  </ul>
</div>

<div id="innercontainer">

  <h1>Create New Request</h1>

<%= hidden_field_tag "request[relevant_skills][]", "" %>

<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <div class = "req-description">
    <%= f.label :description %>
    <%= f.text_area :description %>
    </div>
  </div>
  <div class="field">
    <%= f.hidden_field :employee_id, :value => current_employee.id %>
  </div>

  <div class = "req-dates"> 
    <div class="field">
      <%= f.label :start_date %>
      <%= f.text_field :start_date %>
    </div>
  </div>
  <div class = "req-dates">  
    <div class="field">
      <%= f.label :end_date %>
      <%= f.text_field :end_date %>
    </div>
  </div>

  <div class = "req-select-checkboxes">
    
    <div class="field" id="left-column">
      <ul>
        <li><%= f.label :group %></li>
        <li><%= f.select :group, ['Development', 'Strategy'] %></li>
      </ul>
    </div>
    
  
  <div class="field" id="right-column" >
    <ul> 
      <li><%= f.label :location, "Office" %></li>
      <li><%= f.select :location, ['NY', 'AR', 'IL', 'UK', 'CA'] %></li>
    </ul>
  </div>

<div id="req-skills">
  <div class = "field" >
    <%= f.label :relevant_skills %>
    <% @skills.each do |skill| %>
      <div class = "inbox">
        <%= check_box_tag "relevant_skills[]", skill.language, @request.relevant_skills %>
          <div class = "language"> 
            <%= skill.language %>
          </div>
      </div>   
    <% end %>
  </div>
</div>  
  <div class="field">
    <div class="req-actions">
      <%= f.submit %>
        <div class="req-cancel-new">
          <%= f.submit 'Cancel', :action => 'create', :name => 'cancel_button' %>
        </div>
    </div>
  </div>
<% end %>
</div>
</div>  

app/views/requests/requests_calendar.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
    <li id="selected"><%= link_to 'Requests Calendar', requests_path%></li>
    <li><%= link_to "Requests I've Posted",  'my_requests' %></li>
    <li><%= link_to 'My Profile', employee_path(current_employee) %></li> 
  </ul>
</div>

<div id="innercontainer">

<h1>Requests Calendar</h1><%= link_to "View List", requests_path %>
<div id="requests">

<h2 id="month">
    <%= link_to "<", date: @date.prev_month %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", date: @date.next_month %>
  </h2>
  <%= calendar @date do |date| %>
    <%= date.day %>
    <% if @requests_by_date[date] %>
      <ul>
        <% @requests_by_date[date].each do |request| %>
          <li><%= link_to request.title, request %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</br>
</div>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<div id="tabs"> 
  <ul>
  	<li id="selected"><%= link_to 'Request' %></li>
    <li><%= link_to 'All Requests', requests_path%></li>
    <li><%= link_to "Requests I've Posted", _my_requests_path %></li>
    <li><%= link_to 'My Profile', employee_path(current_employee) %></li> 
  </ul>
</div>

<div id="innercontainer">

<p>
  <b>Request ID:</b> <%= @request.id %>
</p>
<p>
  <b>Request Created By:</b> <%= Employee.find_by_id(@request.employee_id).first_name %> <%= Employee.find_by_id(@request.employee_id).last_name %>
</p>
<p>
  <b>Group:</b> <%= @request.group %>
</p>
<p>
  <b>Office:</b> <%= @request.location %>
</p>
<p>
  <b>Request Title:</b> <%= @request.title %>
</p>
<p>
  <b>Description:</b> <%= @request.description %>
</p>
<p>
  <b>Start Date:</b> <%= @request.start_date %>
</p>
<p>
  <b>End Date:</b> <%= @request.end_date %>
</p>
<p>
  <b>Relevant Skills:</b> <%= @request.relevant_skills %>
</p>

</div>