config/routes.rb
OneteamApp::Application.routes.draw do

  resources :requests do
    get :cancel_request
  end

  get "cancel_request" => "requests#cancel_request", :as => "cancel_request"
 
  resources :skills

  get "calendars/index"

  get "password_resets/new"

  resources :feedbacks
  resources :commissions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "employees#new", :as => "sign_up"
  get "my_requests" => "requests#my_requests", :as => "_my_requests"
  get "requests_calendar" => "requests#requests_calendar", :as => "_requests_calendar"
  get "my_requests_calendar" => "requests#my_requests_calendar", :as => "_my_requests_calendar"
  root :to => "sessions#new" 
  
  resources :requests do 
    resources :responses 
  end

  resources :responses do
      resources :commissions
  end 

  resources :employees
  resources :sessions
  resources :requests
  resources :responses
  resources :password_resets

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :comment, :name

  belongs_to :employee
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully submitted.' }
        format.json { render json: @feedback, status: :created, location: @feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :name, :value => current_employee.name %>
  </div>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Feedback List</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Comment</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.name %></td>
    <td><%= feedback.comment %></td>
    <td><%= feedback.created_at %></td>
    <td><%= link_to 'Show', feedback %></td>    
    <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
    <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</br>

<%= link_to 'Go Back to Requests', requests_path %>

app/views/feedbacks/new.html.erb
<h1>Tell us what you think!</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @feedback.comment %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %>
 |
<%= link_to 'Back to Requests', requests_path %>